version: "3.9"
services:

  music:
    image: kubernetes-multiflavors-go:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "9081:9081"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "27017:27017"

  movie:
    image: kubernetes-multiflavors-python:latest
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          memory: 1024M

  user:
    image: kubernetes-multiflavors-nodejs:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - type: bind
        source: ./docker/postgres.sql
        target: /docker-entrypoint-initdb.d/postgres.sql
    deploy:
      resources:
        limits:
          memory: 1024M

  product:
    image: kubernetes-multiflavors-java:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: product
    deploy:
      resources:
        limits:
          memory: 1024M