version: "3.9"
services:

  user:
    image: microservice-multiflavors:node
    volumes:
      - ./app/user:/app
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password


  movie:
    image: microservice-multiflavors:python
    volumes:
      - ./app/movie:/app
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine